Added Folding!
AyhamAl-Ali/Sk-ST3 pull request #18
Opened 2023-05-21 22:17 UTC by Blazin3330

You can now use Sk-VSC to categorise code inside your skripts.

Example:
```
#!FOLD [NAME]
  > YOUR CODE HERE
#!UNFOLD
```

![skvsc](https://github.com/AyhamAl-Ali/Sk-ST3/assets/61667451/06071d5f-d3c2-4b4b-8a85-0efc2f042dc3)

2023-05-21 22:37 UTC, AyhamAl-Ali requested changes
Good Job! 🚀

Just few minor things

2023-05-21 22:37 UTC, AyhamAl-Ali commented on README.md
> +# Chanelog (v2.5.4)
```suggestion
# Chanelog (v2.6.4)
```

2023-05-21 22:37 UTC, AyhamAl-Ali commented on README.md
> +   > YOUR CODE HERE
```suggestion
> YOUR CODE HERE
```

2023-05-21 22:37 UTC, AyhamAl-Ali commented on VSC/src/CHANGELOG.md
> +# Changelog (v2.5.4)
```suggestion
# Changelog (v2.6.4)
```

2023-05-21 22:37 UTC, AyhamAl-Ali commented on VSC/src/CHANGELOG.md
> +   > YOUR CODE HERE
```suggestion
> YOUR CODE HERE
```

2023-05-21 22:37 UTC, AyhamAl-Ali commented on VSC/src/language-configuration.json
> -    // symbols used as brackets
Keep this comment :\

2023-05-21 22:37 UTC, AyhamAl-Ali commented on VSC/src/language-configuration.json
> -    // symbols that are auto closed when typing
Keep this comment :\

2023-05-21 22:37 UTC, AyhamAl-Ali commented on VSC/src/language-configuration.json
> -    // symbols that can be used to surround a selection
Keep this comment :\

2023-05-21 23:17 UTC, Blazin3330 reviewed
Updated

2023-05-22 12:11 UTC, AyhamAl-Ali commented on VSC/src/language-configuration.json
> -    // symbols used as brackets
Unsolved request.

2023-05-22 12:11 UTC, AyhamAl-Ali commented on VSC/src/language-configuration.json
> -    // symbols that are auto closed when typing
Unsolved request.

2023-06-09 22:59 UTC, AyhamAl-Ali requested changes

2023-06-10 11:07 UTC, AyhamAl-Ali approved these changes

2023-06-10 11:08 UTC, merged